server:
  address: ${SERVER_ADDRESS:localhost}
  port: ${SERVER_PORT:8080}

app:
  version: @APP_VERSION@
  allowed-origins: ${ALLOWED_ORIGINS:http://localhost:5173,http://localhost:4173,https://ryandur.github.io}
